# Generated by Django 6.0.4 on 2026-05-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
