# Generated by Django 6.0.4 on 2026-05-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('ASUS', 'ASUS'), ('MSI', 'MSI'), ('ROG', 'ROG'), ('Logitech', 'Logitech'), ('Razer', 'Razer'), ('Attack Shark', 'Attack Shark'), ('SteelSeries', 'SteelSeries'), ('HyperX', 'HyperX')], max_length=100),
        ),
    ]
